### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by khabach** [SnowVolf/PCompiler#4]
this message always appear to me whene i try to build an project
please help me resolve it

/data/data/com.gmail.heagoo.apkeditor.pro/files/bin/aapt[1]: syntax error: '„1¤7?4„1¤7„1¤74' unexpected

**Comment by anonyamous1111** [comment]
> تظهر لي هذه الرسالة دائمًا عندما أحاول إنشاء مشروع ، 
> الرجاء مساعدتي في حلها
> 
> /data/data/com.gmail.heagoo.apkeditor.pro/files/bin/aapt [1]: خطأ في البنية: "„ 1¤7؟ 4 "1¤7„ 1¤7 ' غير متوقع

**Comment by uy9138416** [comment]
This is not bulid

**Comment by uy9138416** [comment]
Sorry, Bulid is not supported any more. If you bought apk editor pro before, and this is not what you want, please email to heagoo@gmail.com for solutions. ( please with a title of "VERSION 1.9 ISSUES")
