### ISSUE TITLE
https://github.com/SnowVolf/PCompiler/issues/3#issue-379454348

### ISSUE THREAD

**Issue by Ssieef** [SnowVolf/PCompiler#6]
https://github.com/SnowVolf/PCompiler/issues/3#issue-379454348

**Comment by 02629524272** [comment]
https://github.com/SnowVolf/PCompiler/issues/6#issue-555054324

**Comment by 02629524272** [comment]
https://github.com/SnowVolf/PCompiler/issues/6#issuecomment-588609997

**Comment by 02629524272** [comment]
> [#3 (comment)](https://github.com/SnowVolf/PCompiler/issues/3#issue-379454348)

**Comment by 02629524272** [comment]
Duplicate of #

**Comment by 02629524272** [comment]
Duplicate of #

**Comment by 02629524272** [comment]
@SnowVolf

**Comment by uy9138416** [comment]
Issue for the Bulid

**Comment by uy9138416** [comment]
Issue is this app not bulid

**Comment by SnowVolf** [comment]
Fixed [d82fe18](https://github.com/SnowVolf/PCompiler/commit/d82fe18814db2641fcdb1077394ad94ad39a75e2)
